# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: d3d4dc7
_src_path: gh:scipp/copier_template
description: 'Python package to read McStas data and export as python objects in different
    formats or as other files.


    '
max_python: '3.12'
min_python: '3.10'
namespace_package: ''
nightly_deps: scipp,scippnexus
orgname: mccode-dev
prettyname: McStasToX
projectname: McStasToX
related_projects: Scipp,ScippNexus
year: 2025
