name: Docs

on:
  workflow_dispatch:
    inputs:
      publish:
        default: false
        type: boolean
      version:
        default: ''
        required: false
        type: string
      branch:
        description: 'Branch/tag with documentation source. If not set, the current branch will be used.'
        default: ''
        required: false
        type: string
      linkcheck:
        description: 'Run the link checker. If not set the link checker will not be run.'
        default: false
        required: false
        type: boolean
  workflow_call:
    inputs:
      publish:
        default: false
        type: boolean
      version:
        default: ''
        required: false
        type: string
      branch:
        description: 'Branch/tag with documentation source. If not set, the current branch will be used.'
        default: ''
        required: false
        type: string
      linkcheck:
        description: 'Run the link checker. If not set the link checker will not be run.'
        default: false
        required: false
        type: boolean

env:
  VERSION: ${{ inputs.version }}

jobs:
  docs:
    name: Build documentation
    runs-on: 'ubuntu-24.04'
    env:
        ESS_PROTECTED_FILESTORE_USERNAME: ${{ secrets.ESS_PROTECTED_FILESTORE_USERNAME }}
        ESS_PROTECTED_FILESTORE_PASSWORD: ${{ secrets.ESS_PROTECTED_FILESTORE_PASSWORD }}
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ inputs.branch == '' && github.ref_name || inputs.branch }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          fetch-depth: 0  # history required so cmake can determine version
      - run: mkdir -p build/html/
      - uses: prefix-dev/setup-pixi@v0.9.4
        with:
          frozen: true
          environments: docs
      - run: pixi run --locked -e docs docs
      - run: pixi run --frozen -e docs linkcheck
        if: ${{ inputs.linkcheck }}
      - uses: actions/upload-artifact@v7
        id: artifact-upload-step
        with:
          name: docs_html
          path: build/html/
      - run: echo "::notice::https://remote-unzip.deno.dev/${{ github.repository }}/artifacts/${{ steps.artifact-upload-step.outputs.artifact-id }}"
      - uses: JamesIves/github-pages-deploy-action@v4.8.0
        if: ${{ inputs.publish }}
        with:
          branch: gh-pages
          folder: build/html
          single-commit: true
